### ISSUE TITLE
epixiv的设置问题

### ISSUE THREAD

**Issue by Mizuho486** [sanshanya/hoshino_xcw#4]
需要在hoshino的设置文档中添加账号信息吗？我发现你epixiv的设置文件(config.yml)里有账号密码。不知道是有意还是忘记清除了。。是否可以直接使用？

**Comment by Mizuho486** [comment]
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 278, in search_illust
    r = self.no_auth_requests_call('GET', url, params=params, req_auth=req_auth)

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 44, in no_auth_requests_callself.require_auth()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\sit
e-packages\pixivpy3\api.py", line 51, in require_auth
    raise PixivError('Authentication required! Call login() or set_auth() first!
')
pixivpy3.utils.PixivError: Authentication required! Call login() or set_auth() first!

填写自己账号密码以后还是会报错

**Comment by sanshanya** [comment]
epixiv的账号和密码,被移到了_bot_.py的46,47行
setu_mix的apikey同理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sanshanya/hoshino_xcw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 上午8:34
收件人:&nbsp;"sanshanya/hoshino_xcw"<hoshino_xcw@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [sanshanya/hoshino_xcw] epixiv的设置问题 (#4)





 
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 278, in search_illust
 r = self.no_auth_requests_call('GET', url, params=params, req_auth=req_auth)
 
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 44, in no_auth_requests_callself.require_auth()
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\sit
 e-packages\pixivpy3\api.py", line 51, in require_auth
 raise PixivError('Authentication required! Call login() or set_auth() first!
 ')
 pixivpy3.utils.PixivError: Authentication required! Call login() or set_auth() first!
 
填写自己账号密码以后还是会报错

**Comment by Mizuho486** [comment]
> epixiv的账号和密码,被移到了_bot_.py的46,47行 setu_mix的apikey同理
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sanshanya/hoshino_xcw" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月20日(星期五) 上午8:34 收件人:&nbsp;"sanshanya/hoshino_xcw"<hoshino_xcw@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [sanshanya/hoshino_xcw] epixiv的设置问题 (#4) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 278, in search_illust r = self.no_auth_requests_call('GET', url, params=params, req_auth=req_auth) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 44, in no_auth_requests_callself.require_auth() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\sit e-packages\pixivpy3\api.py", line 51, in require_auth raise PixivError('Authentication required! Call login() or set_auth() first! ') pixivpy3.utils.PixivError: Authentication required! Call login() or set_auth() first! 填写自己账号密码以后还是会报错 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是想直接把这个插件放进自己的xcwbot的，不知道是不是还有别处需要修改？在_bot_.py里添加账号信息以后控制台里还是报错

**Comment by sanshanya** [comment]
修改modules\epixiv内的pixiv.py的245行```self.login(hoshino.config.pixiv_id, hoshino.config.pixiv_password)```为```self.login(config.pixiv.username, config.pixiv.password)```,就能以config.yml内账号密码登录




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sanshanya/hoshino_xcw"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 上午9:07
收件人:&nbsp;"sanshanya/hoshino_xcw"<hoshino_xcw@noreply.github.com&gt;;
抄送:&nbsp;"1057069677"<1057069677@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sanshanya/hoshino_xcw] epixiv的设置问题 (#4)





  
epixiv的账号和密码,被移到了_bot_.py的46,47行 setu_mix的apikey同理
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "sanshanya/hoshino_xcw" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月20日(星期五) 上午8:34 收件人:&nbsp;"sanshanya/hoshino_xcw"<hoshino_xcw@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [sanshanya/hoshino_xcw] epixiv的设置问题 (#4) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 278, in search_illust r = self.no_auth_requests_call('GET', url, params=params, req_auth=req_auth) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pixivpy3\aapi.py", line 44, in no_auth_requests_callself.require_auth() File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\sit e-packages\pixivpy3\api.py", line 51, in require_auth raise PixivError('Authentication required! Call login() or set_auth() first! ') pixivpy3.utils.PixivError: Authentication required! Call login() or set_auth() first! 填写自己账号密码以后还是会报错 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
我是想直接把这个插件放进自己的xcwbot的，不知道是不是还有别处需要修改？在_bot_.py里添加账号信息以后控制台里还是报错

**Comment by Mizuho486** [comment]
最后确定是因为代理？之类的原因，我人和服务器都在海外，可能因为这个反而导致连接不上了，不过朋友帮我解决了，但还是谢谢啦！
